package com.productive6.productive.persistence;

import androidx.room.Database;
import androidx.room.RoomDatabase;

import com.productive6.productive.objects.Task;
import com.productive6.productive.persistence.daos.TaskDao;

/**
 * Default database structure code required by Room
 * Implementation is auto-generated by the library.
 */
@Database(entities = {Task.class}, version = 1, exportSchema = false)
public abstract class ProductiveDB extends RoomDatabase {

    public abstract TaskDao getTaskDao();
}
