package com.productive6.productive.persistence.room.access;

import com.productive6.productive.objects.User;

import java.util.List;

/**
 * Interface specifically handling the access of Users in the database.
 */
public interface IUserAccess {


    /**
     * Inserts a new (no-id)
     * task into the database.
     * @param u the task to add.
     * @return the autogenerated id of the user
     */
    long insertUser(User u);

    /**
     * @return a list of all users. Ordering is inspecific.
     */
    List<User> getAllUsers();

    /**
     * Updates the database information of a user
     * which has already been assigned an id
     * @param u the task to update
     */
    void updateUser(User u);
}
